server:
  port: 9090
  
spring:
  cloud:
    gateway:
      routes:
      - id: livro_service_route
#        uri: http://localhost:8080
        uri: lb://livro-service
        predicates:
        - Path=/livros/{segment}
      - id: avalicacao_service_route
#        uri: http://localhost:8081
        uri: lb://avaliacao-service
        predicates:
        - Path=/avaliacoes/{segment}
      - id: admin_route
#        uri: http://localhost:8081
        uri: lb://admin
        predicates:
        - Path=/admin/{segment}
